# Generated by Django 4.2.13 on 2024-05-23 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_pk', models.AutoField(primary_key=True, serialize=False)),
                ('fin_co_no', models.CharField(max_length=20, unique=True)),
                ('kor_co_nm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_pk', models.AutoField(primary_key=True, serialize=False)),
                ('dcls_month', models.TextField()),
                ('fin_prdt_cd', models.CharField(max_length=20, unique=True)),
                ('fin_prdt_nm', models.CharField(max_length=255)),
                ('join_way', models.TextField()),
                ('dcls_strt_day', models.TextField(blank=True, null=True)),
                ('dcls_end_day', models.TextField(blank=True, null=True)),
                ('fin_co_subm_day', models.TextField(blank=True, null=True)),
                ('mrtr_int', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('join_deny', models.TextField(blank=True, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('dly_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_lmt', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_inci_expn', models.TextField(blank=True, null=True)),
                ('erly_rpay_fee', models.TextField(blank=True, null=True)),
                ('bank_type', models.IntegerField(choices=[(1, '예금상품'), (2, '적금상품'), (3, '주택담보대출'), (4, '전세대출')])),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bank')),
                ('like_users', models.ManyToManyField(related_name='like_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.TextField(blank=True, null=True)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('save_trm', models.FloatField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('rsrv_type', models.TextField(blank=True, null=True)),
                ('mrtg_type_nm', models.TextField(blank=True, null=True)),
                ('rpay_type_nm', models.TextField(blank=True, null=True)),
                ('lend_rate_type_nm', models.TextField(blank=True, null=True)),
                ('lend_rate_min', models.TextField(blank=True, null=True)),
                ('lend_rate_max', models.TextField(blank=True, null=True)),
                ('lend_rate_avg', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bank')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoproducts', to='products.product')),
            ],
        ),
    ]
