# Generated by Django 4.2.13 on 2024-05-23 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField()),
                ('kor_co_no', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.TextField()),
                ('cur_num', models.TextField()),
                ('ttb', models.IntegerField(default=0)),
                ('tts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.DateField()),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('back_type', models.IntegerField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='banks.bank')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('product', models.ManyToManyField(related_name='review_comments', to='banks.product')),
                ('user', models.ManyToManyField(related_name='review_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ManyToManyField(related_name='liked_products', to='banks.bank')),
                ('product', models.ManyToManyField(related_name='liked_products', to='banks.product')),
                ('user', models.ManyToManyField(related_name='liked_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_deny', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('intr_rate_type', models.CharField(choices=[('S', '단리'), ('M', '복리')], default='S', max_length=10)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('save_trm', models.IntegerField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('rsrv_type', models.TextField(blank=True, null=True)),
                ('loan_inci_expn', models.TextField(blank=True, null=True)),
                ('erly_rpay_fee', models.TextField(blank=True, null=True)),
                ('dly_rate', models.TextField(blank=True, null=True)),
                ('rpay_type_nm', models.TextField(blank=True, null=True)),
                ('lend_rate_type_nm', models.TextField(blank=True, null=True)),
                ('lend_rate_min', models.FloatField(blank=True, null=True)),
                ('lend_rate_max', models.FloatField(blank=True, null=True)),
                ('lend_rate_avg', models.FloatField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_products', to='banks.bank')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_products', to='banks.product')),
            ],
        ),
    ]
